### ISSUE TITLE
Underscore in the name doesn't looks alright.

### ISSUE THREAD

**Issue by unixbhaskar** [gokrazy/stat#1]
Michael,

What is the rationale behind that naming scheme??? It looks ugly and pointless. Could you please correct them to plain, strip off the underscore. 

Believe me, it will look much saner, than what is looking now. 

I know, **it's bloody nit-picking** ..but hoping it worth one.YMMV. OR did I grossly missed the "importance" of those underscores???? Not sure though.

**Comment by stapelberg** [comment]
The original dstat underlined column headers:
![headers](https://user-images.githubusercontent.com/55506/86050680-7a4b5d00-ba54-11ea-8e13-188f0b883e64.jpg)

To align the output correctly in the terminal, I used explicit underscore symbols to distinguish space and alignment characters. Using underscore instead of the underline ANSI code (like dstat) was just easier.

We should be able to replace them with spaces; that shouldn’t break the alignment.
